ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Scanner Synth"
ENT.Author 			= "Zippy"
ENT.Contact 		= "http://vrejgaming.webs.com/"
ENT.Purpose 		= ""
ENT.Instructions	= ""
ENT.Category		= ""